version: 2.1
orbs:
  node: circleci/node@1.1

jobs:
  integration-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install PIP
          command: sudo apt-get install python-pip python-dev
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy application
          command: |
            chmod +x scripts/aws-cli-assumerole.sh
            source scripts/aws-cli-assumerole.sh    
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run test # run our integration tests
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install PIP
          command: sudo apt-get install python-pip python-dev
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy application
          command: |
            chmod +x scripts/aws-cli-assumerole.sh
            source scripts/aws-cli-assumerole.sh  
      - node/with-cache:
          steps:
            - run: npm run sls -- deploy
  acceptance-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run acceptance # run our acceptance tests

workflows:
   version: 2
   dev:
     jobs:
       - integration-test
       - deploy:
          requires:
            - integration-test
       - acceptance-test:
          requires:
            - deploy